---
- name: Generate User Data
  hosts: localhost 
  gather_facts: false
  tasks:
  - name: Ensure user bob is created and use custom credentials to create the user
    community.windows.win_domain_user:
      name: bob
      firstname: Bob
      surname: Smith
      password: B0bP4ssw0rd
      state: present
